# Generated by Django 5.2.8 on 2025-11-16 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cashregister_proforma_proformaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_threshold', models.DecimalField(decimal_places=2, default=10.0, help_text='Remises supérieures à ce pourcentage nécessitent validation', max_digits=5, verbose_name='Seuil de remise (%)')),
                ('cash_difference_threshold', models.DecimalField(decimal_places=2, default=5.0, help_text='Écarts supérieurs à ce pourcentage nécessitent validation', max_digits=5, verbose_name="Seuil d'écart de caisse (%)")),
                ('stock_adjust_threshold', models.IntegerField(default=10, help_text='Ajustements supérieurs à ce nombre nécessitent validation', verbose_name="Seuil d'ajustement stock")),
                ('require_validation_sale_cancel', models.BooleanField(default=True, verbose_name='Validation pour annulation vente')),
                ('require_validation_price_change', models.BooleanField(default=True, verbose_name='Validation pour modification prix')),
                ('require_validation_refund', models.BooleanField(default=True, verbose_name='Validation pour remboursement')),
                ('require_validation_product_delete', models.BooleanField(default=True, verbose_name='Validation pour suppression produit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validators', models.ManyToManyField(help_text='Utilisateurs pouvant valider les opérations sensibles', related_name='can_validate', to=settings.AUTH_USER_MODEL, verbose_name='Validateurs autorisés')),
            ],
            options={
                'verbose_name': 'Configuration Validation',
                'verbose_name_plural': 'Configurations Validation',
                'db_table': 'validation_settings',
            },
        ),
        migrations.CreateModel(
            name='SupervisorValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('discount', 'Remise importante'), ('price_change', 'Modification de prix'), ('sale_cancel', 'Annulation de vente'), ('cash_close', 'Fermeture caisse avec écart'), ('refund', 'Remboursement'), ('stock_adjust', 'Ajustement stock important'), ('product_delete', 'Suppression produit')], max_length=20, verbose_name="Type d'opération")),
                ('operation_description', models.TextField(verbose_name='Description')),
                ('operation_data', models.JSONField(default=dict, verbose_name="Données de l'opération")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=10, verbose_name='Statut')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Notes de validation')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP demandeur')),
                ('validated_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP validateur')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_performed', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Validation Superviseur',
                'verbose_name_plural': 'Validations Superviseur',
                'db_table': 'supervisor_validations',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['-requested_at'], name='supervisor__request_27335d_idx'), models.Index(fields=['status'], name='supervisor__status_673056_idx'), models.Index(fields=['operation_type'], name='supervisor__operati_c020ab_idx')],
            },
        ),
    ]
