# Generated by Django 4.2.7 on 2025-11-19 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_validationsettings_supervisorvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('password_reset', 'Réinitialisation mot de passe'), ('create_sale', 'Création vente'), ('update_stock', 'Modification stock'), ('delete_product', 'Suppression produit'), ('other', 'Autre')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal utilisateur',
                'verbose_name_plural': 'Journaux utilisateurs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
