# Generated by Django 4.2.7 on 2025-11-20 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='inventory.customer', verbose_name='Client'),
        ),
    ]
