# Generated by Django 5.2.8 on 2025-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_salesorder_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(default='1234', max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de caisse',
                'verbose_name_plural': 'Paramètres de caisse',
            },
        ),
    ]
