# Generated by Django for profile image field
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_cashregistersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Photo de profil'),
        ),
    ]
